cas:
  server:
    name: http://cas2:8080
    prefix: http://cas2:8080/cas

cas.serviceRegistry:
  json.location: file:///etc/cas/config/services
  initFromJson: true


cas.ticket:
  registry:
    ignite.keyAlgorithm:
    ignite.protocol:
    ignite.trustStorePassword:
    ignite.keyStoreType:
    ignite.keyStoreFilePath:
    ignite.keyStorePassword:
    ignite.trustStoreType:
    ignite.igniteAddress[0]: cas1:47500
    ignite.igniteAddress[1]: cas2:47500
    ignite.trustStoreFilePath:
    #ignite.ackTimeout: 2000
    #ignite.joinTimeout: 1000
    ignite.localAddress:
    #ignite.localPort: -1
    #ignite.networkTimeout: 5000
    #ignite.socketTimeout: 5000
    #ignite.threadPriority: 10
    ignite.forceServerMode: false
    ignite.clientMode: false

    ignite.ticketsCache.writeSynchronizationMode: FULL_SYNC
    ignite.ticketsCache.atomicityMode: TRANSACTIONAL
    ignite.ticketsCache.cacheMode: REPLICATED

    ignite.crypto.signing.key:
    #ignite.crypto.signing.keySize: 512
    ignite.crypto.encryption.key:
    #ignite.crypto.encryption.keySize: 16
    ignite.crypto.alg: AES
    ignite.crypto.enabled: false



cas.authn.oidc.issuer: liferay
cas.authn.oidc.claims: org,sub,name,preferred_username,family_name
