version: '3.4'
services:
  cas1:
    image: tomcat:8.0-jre8 
    volumes:
      - ../../cas/build/libs/cas.war:/usr/local/tomcat/webapps/cas.war
      - ../../config/cas1:/etc/cas/config 
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh   
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml 
    ports:
      - 8444:8080
      - 5005:8011
    expose:
      - "8009"
    command: catalina.sh jpda run
  cas2:
    image: tomcat:8.0-jre8 
    volumes:
      - ../../cas/build/libs/cas.war:/usr/local/tomcat/webapps/cas.war
      - ../../config/cas2:/etc/cas/config 
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh   
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml 
    ports:
      - 8445:8080
      - 5006:8011
    expose:
      - "8009"
    command: catalina.sh jpda run
  casmg:
    image: tomcat:8.0-jre8 
    volumes:
      - ../../cas-management/build/libs/cas-management.war:/usr/local/tomcat/webapps/cas-management.war
      - ../../config/casmg:/etc/cas/config
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh  
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml     
    ports:
      - 8446:8080
      - 5007:8011
    expose:
      - "8009"
    command: catalina.sh jpda run
  hsqldb:
    image: datagrip/hsqldb
    expose:
      - "9001"